openapi: 3.0.3
info:
  version: 1.0.0
  title: chirimen api server for raspberry pi
  license:
    name: MIT
paths:
  /gpio/access:
    post:
      summary: GPIO Access
      operationId: gpioAccess
      tags:
        - gpio
      responses:
        '200':
          description: A GPIO Access
  /gpio/ports-get:
    get:
      summary: GPIO
      operationId: gpioPortsGet
      tags:
        - gpio
      parameters:
        - name: portNumber
          in: query
          description: port number
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
  /i2c/access:
    post:
      summary: I2C Access
      operationId: i2cAccess
      tags:
        - i2c
      responses:
        '200':
          description: A I2C Access OK
  /i2c/ports-get:
    get:
      summary: I2C
      operationId: i2cPortsGet
      tags:
        - i2c
      parameters:
        - name: portNumber
          in: query
          description: port number
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200': null
